[package]
name = "proc"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true


[dependencies]
proc-macro2 = "0.4.27"
syn = { version = "0.15.27", features = ["full"] }
quote = "0.6.3"
